export const PERMISSIONS = Object.freeze({
  access_control: {
    view_users: "view_users",
    create_users: "create_users",
    edit_users: "edit_users",
    delete_users: "delete_users",
    manage_roles: "manage_roles",
    manage_permissions: "manage_permissions",
  },
  subjects: {
    view_subjects: "view_subjects",
    create_subjects: "create_subjects",
    edit_subjects: "edit_subjects",
    delete_subjects: "delete_subjects",
    assign_teacher_subjects: "assign_teacher_subjects",
  },
  classes: {
    view_classes: "view_classes",
    create_classes: "create_classes",
    edit_classes: "edit_classes",
    delete_classes: "delete_classes",
    manage_enrollments: "manage_enrollments",
    view_students: "view_students",
  },
  lessons_activities: {
    view_lessons: "view_lessons",
    create_lessons: "create_lessons",
    edit_lessons: "edit_lessons",
    delete_lessons: "delete_lessons",
    schedule_lessons: "schedule_lessons",
    view_activities: "view_activities",
    create_activities: "create_activities",
    edit_activities: "edit_activities",
    delete_activities: "delete_activities",
    grade_activities: "grade_activities",
    view_academic_units: "view_academic_units",
    create_academic_units: "create_academic_units",
    edit_academic_units: "edit_academic_units",
    delete_academic_units: "delete_academic_units",
    close_academic_units: "close_academic_units",
  },
  communication: {
    view_doubts: "view_doubts",
    create_doubts: "create_doubts",
    respond_doubts: "respond_doubts",
    resolve_doubts: "resolve_doubts",
    delete_doubts: "delete_doubts",
    view_notifications: "view_notifications",
    create_notifications: "create_notifications",
    edit_notifications: "edit_notifications",
    delete_notifications: "delete_notifications",
    schedule_notifications: "schedule_notifications",
    view_templates: "view_templates",
    create_templates: "create_templates",
    edit_templates: "edit_templates",
    delete_templates: "delete_templates",
    use_templates: "use_templates",
    view_alerts: "view_alerts",
    create_alerts: "create_alerts",
    mark_alerts_read: "mark_alerts_read",
  },
  reports_analytics: {
    view_reports: "view_reports",
    create_reports: "create_reports",
    edit_reports: "edit_reports",
    delete_reports: "delete_reports",
    schedule_reports: "schedule_reports",
    export_reports: "export_reports",
    view_analytics: "view_analytics",
    view_kpis: "view_kpis",
    manage_dashboard: "manage_dashboard",
    view_report_templates: "view_report_templates",
    create_report_templates: "create_report_templates",
    edit_report_templates: "edit_report_templates",
    delete_report_templates: "delete_report_templates",
  },
});
